[package]
name = "unextendr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1"
libR-sys = { git = "https://github.com/extendr/libR-sys" }
once_cell = "1"
thiserror = "1"
